-- Agro Sky — migración 0100: corrige numeración de facturas + valida stock antes de crear la venta
-- Ejecutar una sola vez en Supabase: Dashboard > SQL Editor > New query > pegar > Run
--
-- El usuario reportó que sus últimas 2 facturas reales salieron con
-- numero_factura 52 y 53 en vez de 39 y 40 (las correctas eran 37 y 38).
-- Causa raíz: numero_factura es "generated always as identity" -- ese
-- contador NUNCA retrocede, ni al borrar una fila ni al hacer rollback de
-- una transacción. crear_venta_interna validaba el stock DESPUÉS de
-- insertar la fila en "ventas": si algún ítem no tenía stock suficiente,
-- la función abortaba (correcto, la venta no queda creada), pero el
-- número de factura ya se había consumido y se pierde para siempre. Esto
-- ya había pasado una vez antes (ver migración 0036_reset_numero_factura).
--
-- Confirmado con el usuario (2026-08-19): las facturas 52/53 (Argelis
-- Barahona $1,410.25 del 18/ago, Drones Industriales $350 del 19/ago)
-- todavía no se le entregaron a esos clientes, así que es seguro
-- renumerarlas a 39/40 sin que quede un PDF ya entregado con un número
-- distinto al del sistema.
--
-- Una columna "generated always as identity" no se puede corregir con un
-- UPDATE normal (Postgres lo rechaza: "column can only be updated to
-- DEFAULT"). Se cambia a "generated by default as identity" -- mismo
-- comportamiento automático en cada insert (la app nunca manda
-- numero_factura a mano, siempre lo genera Postgres), pero ahora sí
-- admite una corrección manual como esta si algún día vuelve a hacer
-- falta, sin este mismo problema.
alter table ventas alter column numero_factura set generated by default;

update ventas set numero_factura = 39 where id = 'dad09bec-b37e-40db-a060-7f9e900f9f7f';
update ventas set numero_factura = 40 where id = '42e4f1a8-d9fa-4438-a6b3-21df25511f93';

alter table ventas alter column numero_factura restart with 41;

-- Misma firma de parámetros que la versión anterior (migración 0037) --
-- create or replace alcanza, no hace falta dropear primero. Único cambio
-- real: el chequeo de stock (nuevo bucle, con "select ... for update" para
-- no permitir que 2 ventas concurrentes le resten al mismo producto sin
-- verse una a la otra) se mueve ANTES del insert en "ventas", así que si
-- falta stock la función nunca llega a crear la fila ni a consumir un
-- numero_factura.
create or replace function crear_venta_interna(
  p_fecha date,
  p_cliente_nombre text,
  p_cliente_documento text,
  p_cliente_ruc text,
  p_cliente_ruc_dv text,
  p_cliente_telefono text,
  p_cliente_direccion text,
  p_cliente_correo text,
  p_nota text,
  p_estado_pago text,
  p_fecha_vencimiento date,
  p_items jsonb
)
returns uuid
language plpgsql
security definer
as $$
declare
  v_venta_id uuid;
  v_item jsonb;
  v_tipo text;
  v_cantidad numeric(12, 2);
  v_precio numeric(12, 2);
  v_aplica_itbms boolean;
  v_item_subtotal numeric(12, 2);
  v_subtotal_gravado numeric(12, 2) := 0;
  v_subtotal_exento numeric(12, 2) := 0;
  v_itbms numeric(12, 2);
  v_total numeric(12, 2);
  v_filas_afectadas int;
  v_stock_actual integer;
begin
  if p_items is null or jsonb_array_length(p_items) = 0 then
    raise exception 'La venta debe tener al menos un producto o servicio';
  end if;

  if p_estado_pago not in ('pagada', 'pendiente') then
    raise exception 'Estado de pago invalido';
  end if;

  if p_estado_pago = 'pendiente' and p_fecha_vencimiento is null then
    raise exception 'Falta la fecha de vencimiento para una venta por cobrar';
  end if;

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    v_tipo := v_item ->> 'tipo';
    v_cantidad := (v_item ->> 'cantidad')::numeric;
    v_precio := (v_item ->> 'precio_unitario')::numeric;
    v_aplica_itbms := v_tipo in ('nuevo', 'usado');
    v_item_subtotal := round(v_cantidad * v_precio, 2);

    if v_aplica_itbms then
      v_subtotal_gravado := v_subtotal_gravado + v_item_subtotal;
    else
      v_subtotal_exento := v_subtotal_exento + v_item_subtotal;
    end if;
  end loop;

  v_itbms := round(v_subtotal_gravado * 0.07, 2);
  v_total := v_subtotal_gravado + v_subtotal_exento + v_itbms;

  -- Validar stock de TODOS los items antes de tocar "ventas" -- ver nota
  -- de la migración arriba.
  for v_item in select * from jsonb_array_elements(p_items)
  loop
    v_tipo := v_item ->> 'tipo';
    if v_tipo in ('nuevo', 'usado') then
      v_cantidad := (v_item ->> 'cantidad')::numeric;

      select cantidad into v_stock_actual
      from productos
      where id = (v_item ->> 'producto_id')::uuid
      for update;

      if v_stock_actual is null or v_stock_actual < v_cantidad::integer then
        raise exception 'No hay stock suficiente para "%"', v_item ->> 'descripcion';
      end if;
    end if;
  end loop;

  insert into ventas (
    fecha, cliente_nombre, cliente_documento, cliente_ruc, cliente_ruc_dv,
    cliente_telefono, cliente_direccion, cliente_correo, nota,
    estado_pago, fecha_vencimiento,
    subtotal_gravado, subtotal_exento, itbms, total, registrado_por
  )
  values (
    p_fecha, p_cliente_nombre, nullif(p_cliente_documento, ''), nullif(p_cliente_ruc, ''), nullif(p_cliente_ruc_dv, ''),
    nullif(p_cliente_telefono, ''), nullif(p_cliente_direccion, ''), nullif(p_cliente_correo, ''), nullif(p_nota, ''),
    p_estado_pago, p_fecha_vencimiento,
    v_subtotal_gravado, v_subtotal_exento, v_itbms, v_total, auth.uid()
  )
  returning id into v_venta_id;

  -- Guarda/actualiza el cliente en el registro reutilizable -- solo con
  -- ventas reales (nunca con cotizaciones, pedido explicito del usuario).
  -- Si ya existia (mismo nombre), completa los campos que llegaron esta vez
  -- sin borrar los que ya se sabian y esta vez no se volvieron a escribir.
  insert into clientes (nombre, cedula, ruc, ruc_dv, telefono, direccion, correo)
  values (
    p_cliente_nombre, nullif(p_cliente_documento, ''), nullif(p_cliente_ruc, ''), nullif(p_cliente_ruc_dv, ''),
    nullif(p_cliente_telefono, ''), nullif(p_cliente_direccion, ''), nullif(p_cliente_correo, '')
  )
  on conflict (nombre) do update set
    cedula = coalesce(excluded.cedula, clientes.cedula),
    ruc = coalesce(excluded.ruc, clientes.ruc),
    ruc_dv = coalesce(excluded.ruc_dv, clientes.ruc_dv),
    telefono = coalesce(excluded.telefono, clientes.telefono),
    direccion = coalesce(excluded.direccion, clientes.direccion),
    correo = coalesce(excluded.correo, clientes.correo),
    actualizado_en = now();

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    v_tipo := v_item ->> 'tipo';
    v_cantidad := (v_item ->> 'cantidad')::numeric;
    v_precio := (v_item ->> 'precio_unitario')::numeric;
    v_aplica_itbms := v_tipo in ('nuevo', 'usado');
    v_item_subtotal := round(v_cantidad * v_precio, 2);

    insert into venta_items (
      venta_id, tipo, producto_id, servicio_id, codigo, descripcion,
      cantidad, precio_unitario, aplica_itbms, subtotal
    )
    values (
      v_venta_id,
      v_tipo,
      nullif(v_item ->> 'producto_id', '')::uuid,
      nullif(v_item ->> 'servicio_id', '')::uuid,
      v_item ->> 'codigo',
      v_item ->> 'descripcion',
      v_cantidad,
      v_precio,
      v_aplica_itbms,
      v_item_subtotal
    );

    if v_tipo in ('nuevo', 'usado') then
      update productos
      set cantidad = cantidad - v_cantidad::integer
      where id = (v_item ->> 'producto_id')::uuid
        and cantidad >= v_cantidad::integer;

      get diagnostics v_filas_afectadas = row_count;
      if v_filas_afectadas = 0 then
        raise exception 'No hay stock suficiente para "%"', v_item ->> 'descripcion';
      end if;
    end if;
  end loop;

  return v_venta_id;
end;
$$;
